name: minicat
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.24
  - scipy>=1.10
  - ase>=3.22.1
  # RDKit is best installed via conda-forge
  - rdkit>=2022.09.1
  - pip
  - pip:
      - .
